import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Support — Red Dot Audit", description: "Purchase, report-access, correction and source support for Red Dot Audit." };

export default async function SupportPage({ searchParams }: { searchParams?: Promise<{ target?: string }> }) {
  const target = (await searchParams)?.target?.trim();
  const scanSubject = encodeURIComponent(`Request a Red Dot scan${target ? ` — ${target}` : ""}`);
  const scanBody = encodeURIComponent(`Jurisdiction: ${target || "[city or county, state]"}\n\nPlease let me know when a source-backed preliminary scan is available.`);
  return <main className="legal-page"><header className="legal-topbar"><Link className="brand" href="/"><span className="brand-mark" aria-hidden="true"><span /></span><span>RED DOT AUDIT</span></Link><Link href="/">Return to scan</Link></header><article className="support-document"><div><p className="eyebrow">SUPPORT</p><h1>How can we help?</h1><p>For purchase access, source corrections, official responses or general questions, contact the appropriate desk below.</p></div>{target && <a className="scan-request-banner" href={`mailto:support@reddotaudit.com?subject=${scanSubject}&body=${scanBody}`}><span><small>REQUEST A SOURCE-BACKED SCAN</small><b>{target}</b></span><strong>Send request →</strong></a>}<div className="support-grid"><a href="mailto:support@reddotaudit.com?subject=Order%20or%20report%20access"><span>ORDER SUPPORT</span><strong>Report access or payment issue</strong><p>Include the checkout email, jurisdiction and purchase date. Never send card details.</p><b>support@reddotaudit.com →</b></a><a href="mailto:support@reddotaudit.com?subject=Source%20correction%20or%20official%20response"><span>EVIDENCE DESK</span><strong>Correction or official response</strong><p>Send the target name, disputed statement and the record or source that resolves it.</p><b>Submit evidence →</b></a><a href="mailto:support@reddotaudit.com?subject=General%20inquiry"><span>GENERAL</span><strong>Professional and press inquiries</strong><p>Questions about methodology, coverage, licensing or institutional use.</p><b>Contact Red Dot Audit →</b></a></div><aside><b>Response standard</b><p>We aim to acknowledge support requests within two business days. Evidence submissions may require additional review.</p></aside></article><footer className="legal-footer"><span>RedDotAudit.com · Follow the record.</span><nav><Link href="/methodology">Methodology</Link><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/refunds">Refunds</Link></nav></footer></main>;
}
